/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "appguard.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(appguard_AppGuardTcpConnection, appguard_AppGuardTcpConnection, AUTO)


PB_BIND(appguard_AppGuardIpInfo, appguard_AppGuardIpInfo, 2)


PB_BIND(appguard_AppGuardTcpInfo, appguard_AppGuardTcpInfo, 2)


PB_BIND(appguard_AppGuardHttpRequest, appguard_AppGuardHttpRequest, 2)


PB_BIND(appguard_AppGuardHttpRequest_HeadersEntry, appguard_AppGuardHttpRequest_HeadersEntry, AUTO)


PB_BIND(appguard_AppGuardHttpRequest_QueryEntry, appguard_AppGuardHttpRequest_QueryEntry, AUTO)


PB_BIND(appguard_AppGuardHttpResponse, appguard_AppGuardHttpResponse, 2)


PB_BIND(appguard_AppGuardHttpResponse_HeadersEntry, appguard_AppGuardHttpResponse_HeadersEntry, AUTO)


PB_BIND(appguard_AppGuardSmtpRequest, appguard_AppGuardSmtpRequest, 2)


PB_BIND(appguard_AppGuardSmtpRequest_HeadersEntry, appguard_AppGuardSmtpRequest_HeadersEntry, AUTO)


PB_BIND(appguard_AppGuardSmtpResponse, appguard_AppGuardSmtpResponse, 2)


PB_BIND(appguard_AppGuardResponse, appguard_AppGuardResponse, AUTO)


PB_BIND(appguard_AppGuardTcpResponse, appguard_AppGuardTcpResponse, 2)





