/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_APPGUARD_APPGUARD_PB_H_INCLUDED
#define PB_APPGUARD_APPGUARD_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _appguard_FirewallPolicy {
    appguard_FirewallPolicy_UNKNOWN = 0,
    appguard_FirewallPolicy_ALLOW = 1,
    appguard_FirewallPolicy_DENY = 2
} appguard_FirewallPolicy;

/* Struct definitions */
typedef struct _appguard_AppGuardTcpConnection {
    pb_callback_t source_ip;
    bool has_source_port;
    uint32_t source_port;
    pb_callback_t destination_ip;
    bool has_destination_port;
    uint32_t destination_port;
    pb_callback_t protocol;
} appguard_AppGuardTcpConnection;

typedef struct _appguard_AppGuardIpInfo {
    pb_callback_t ip;
    pb_callback_t country;
    pb_callback_t asn;
    pb_callback_t org;
    pb_callback_t continent_code;
    pb_callback_t city;
    pb_callback_t region;
    pb_callback_t postal;
    pb_callback_t timezone;
    uint32_t blacklist;
} appguard_AppGuardIpInfo;

typedef struct _appguard_AppGuardTcpInfo {
    bool has_connection;
    appguard_AppGuardTcpConnection connection;
    bool has_ip_info;
    appguard_AppGuardIpInfo ip_info;
    uint64_t tcp_id;
} appguard_AppGuardTcpInfo;

typedef struct _appguard_AppGuardHttpRequest {
    pb_callback_t original_url;
    pb_callback_t headers;
    pb_callback_t method;
    pb_callback_t body;
    pb_callback_t query;
    bool has_tcp_info;
    appguard_AppGuardTcpInfo tcp_info;
} appguard_AppGuardHttpRequest;

typedef struct _appguard_AppGuardHttpRequest_HeadersEntry {
    pb_callback_t key;
    pb_callback_t value;
} appguard_AppGuardHttpRequest_HeadersEntry;

typedef struct _appguard_AppGuardHttpRequest_QueryEntry {
    pb_callback_t key;
    pb_callback_t value;
} appguard_AppGuardHttpRequest_QueryEntry;

typedef struct _appguard_AppGuardHttpResponse {
    uint32_t code;
    pb_callback_t headers;
    bool has_tcp_info;
    appguard_AppGuardTcpInfo tcp_info;
} appguard_AppGuardHttpResponse;

typedef struct _appguard_AppGuardHttpResponse_HeadersEntry {
    pb_callback_t key;
    pb_callback_t value;
} appguard_AppGuardHttpResponse_HeadersEntry;

typedef struct _appguard_AppGuardSmtpRequest {
    pb_callback_t headers;
    pb_callback_t body;
    bool has_tcp_info;
    appguard_AppGuardTcpInfo tcp_info;
} appguard_AppGuardSmtpRequest;

typedef struct _appguard_AppGuardSmtpRequest_HeadersEntry {
    pb_callback_t key;
    pb_callback_t value;
} appguard_AppGuardSmtpRequest_HeadersEntry;

typedef struct _appguard_AppGuardSmtpResponse {
    bool has_code;
    uint32_t code;
    bool has_tcp_info;
    appguard_AppGuardTcpInfo tcp_info;
} appguard_AppGuardSmtpResponse;

typedef struct _appguard_AppGuardResponse {
    appguard_FirewallPolicy policy;
} appguard_AppGuardResponse;

typedef struct _appguard_AppGuardTcpResponse {
    bool has_tcp_info;
    appguard_AppGuardTcpInfo tcp_info;
} appguard_AppGuardTcpResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _appguard_FirewallPolicy_MIN appguard_FirewallPolicy_UNKNOWN
#define _appguard_FirewallPolicy_MAX appguard_FirewallPolicy_DENY
#define _appguard_FirewallPolicy_ARRAYSIZE ((appguard_FirewallPolicy)(appguard_FirewallPolicy_DENY+1))












#define appguard_AppGuardResponse_policy_ENUMTYPE appguard_FirewallPolicy



/* Initializer values for message structs */
#define appguard_AppGuardTcpConnection_init_default {{{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define appguard_AppGuardIpInfo_init_default     {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define appguard_AppGuardTcpInfo_init_default    {false, appguard_AppGuardTcpConnection_init_default, false, appguard_AppGuardIpInfo_init_default, 0}
#define appguard_AppGuardHttpRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, appguard_AppGuardTcpInfo_init_default}
#define appguard_AppGuardHttpRequest_HeadersEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define appguard_AppGuardHttpRequest_QueryEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define appguard_AppGuardHttpResponse_init_default {0, {{NULL}, NULL}, false, appguard_AppGuardTcpInfo_init_default}
#define appguard_AppGuardHttpResponse_HeadersEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define appguard_AppGuardSmtpRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}, false, appguard_AppGuardTcpInfo_init_default}
#define appguard_AppGuardSmtpRequest_HeadersEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define appguard_AppGuardSmtpResponse_init_default {false, 0, false, appguard_AppGuardTcpInfo_init_default}
#define appguard_AppGuardResponse_init_default   {_appguard_FirewallPolicy_MIN}
#define appguard_AppGuardTcpResponse_init_default {false, appguard_AppGuardTcpInfo_init_default}
#define appguard_AppGuardTcpConnection_init_zero {{{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define appguard_AppGuardIpInfo_init_zero        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define appguard_AppGuardTcpInfo_init_zero       {false, appguard_AppGuardTcpConnection_init_zero, false, appguard_AppGuardIpInfo_init_zero, 0}
#define appguard_AppGuardHttpRequest_init_zero   {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, appguard_AppGuardTcpInfo_init_zero}
#define appguard_AppGuardHttpRequest_HeadersEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define appguard_AppGuardHttpRequest_QueryEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define appguard_AppGuardHttpResponse_init_zero  {0, {{NULL}, NULL}, false, appguard_AppGuardTcpInfo_init_zero}
#define appguard_AppGuardHttpResponse_HeadersEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define appguard_AppGuardSmtpRequest_init_zero   {{{NULL}, NULL}, {{NULL}, NULL}, false, appguard_AppGuardTcpInfo_init_zero}
#define appguard_AppGuardSmtpRequest_HeadersEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define appguard_AppGuardSmtpResponse_init_zero  {false, 0, false, appguard_AppGuardTcpInfo_init_zero}
#define appguard_AppGuardResponse_init_zero      {_appguard_FirewallPolicy_MIN}
#define appguard_AppGuardTcpResponse_init_zero   {false, appguard_AppGuardTcpInfo_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define appguard_AppGuardTcpConnection_source_ip_tag 1
#define appguard_AppGuardTcpConnection_source_port_tag 2
#define appguard_AppGuardTcpConnection_destination_ip_tag 3
#define appguard_AppGuardTcpConnection_destination_port_tag 4
#define appguard_AppGuardTcpConnection_protocol_tag 5
#define appguard_AppGuardIpInfo_ip_tag           1
#define appguard_AppGuardIpInfo_country_tag      2
#define appguard_AppGuardIpInfo_asn_tag          3
#define appguard_AppGuardIpInfo_org_tag          4
#define appguard_AppGuardIpInfo_continent_code_tag 5
#define appguard_AppGuardIpInfo_city_tag         6
#define appguard_AppGuardIpInfo_region_tag       7
#define appguard_AppGuardIpInfo_postal_tag       8
#define appguard_AppGuardIpInfo_timezone_tag     9
#define appguard_AppGuardIpInfo_blacklist_tag    100
#define appguard_AppGuardTcpInfo_connection_tag  1
#define appguard_AppGuardTcpInfo_ip_info_tag     2
#define appguard_AppGuardTcpInfo_tcp_id_tag      3
#define appguard_AppGuardHttpRequest_original_url_tag 1
#define appguard_AppGuardHttpRequest_headers_tag 2
#define appguard_AppGuardHttpRequest_method_tag  3
#define appguard_AppGuardHttpRequest_body_tag    4
#define appguard_AppGuardHttpRequest_query_tag   5
#define appguard_AppGuardHttpRequest_tcp_info_tag 100
#define appguard_AppGuardHttpRequest_HeadersEntry_key_tag 1
#define appguard_AppGuardHttpRequest_HeadersEntry_value_tag 2
#define appguard_AppGuardHttpRequest_QueryEntry_key_tag 1
#define appguard_AppGuardHttpRequest_QueryEntry_value_tag 2
#define appguard_AppGuardHttpResponse_code_tag   1
#define appguard_AppGuardHttpResponse_headers_tag 2
#define appguard_AppGuardHttpResponse_tcp_info_tag 100
#define appguard_AppGuardHttpResponse_HeadersEntry_key_tag 1
#define appguard_AppGuardHttpResponse_HeadersEntry_value_tag 2
#define appguard_AppGuardSmtpRequest_headers_tag 1
#define appguard_AppGuardSmtpRequest_body_tag    2
#define appguard_AppGuardSmtpRequest_tcp_info_tag 100
#define appguard_AppGuardSmtpRequest_HeadersEntry_key_tag 1
#define appguard_AppGuardSmtpRequest_HeadersEntry_value_tag 2
#define appguard_AppGuardSmtpResponse_code_tag   1
#define appguard_AppGuardSmtpResponse_tcp_info_tag 100
#define appguard_AppGuardResponse_policy_tag     2
#define appguard_AppGuardTcpResponse_tcp_info_tag 1

/* Struct field encoding specification for nanopb */
#define appguard_AppGuardTcpConnection_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   source_ip,         1) \
X(a, STATIC,   OPTIONAL, UINT32,   source_port,       2) \
X(a, CALLBACK, OPTIONAL, STRING,   destination_ip,    3) \
X(a, STATIC,   OPTIONAL, UINT32,   destination_port,   4) \
X(a, CALLBACK, SINGULAR, STRING,   protocol,          5)
#define appguard_AppGuardTcpConnection_CALLBACK pb_default_field_callback
#define appguard_AppGuardTcpConnection_DEFAULT NULL

#define appguard_AppGuardIpInfo_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   ip,                1) \
X(a, CALLBACK, OPTIONAL, STRING,   country,           2) \
X(a, CALLBACK, OPTIONAL, STRING,   asn,               3) \
X(a, CALLBACK, OPTIONAL, STRING,   org,               4) \
X(a, CALLBACK, OPTIONAL, STRING,   continent_code,    5) \
X(a, CALLBACK, OPTIONAL, STRING,   city,              6) \
X(a, CALLBACK, OPTIONAL, STRING,   region,            7) \
X(a, CALLBACK, OPTIONAL, STRING,   postal,            8) \
X(a, CALLBACK, OPTIONAL, STRING,   timezone,          9) \
X(a, STATIC,   SINGULAR, UINT32,   blacklist,       100)
#define appguard_AppGuardIpInfo_CALLBACK pb_default_field_callback
#define appguard_AppGuardIpInfo_DEFAULT NULL

#define appguard_AppGuardTcpInfo_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  connection,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ip_info,           2) \
X(a, STATIC,   SINGULAR, UINT64,   tcp_id,            3)
#define appguard_AppGuardTcpInfo_CALLBACK NULL
#define appguard_AppGuardTcpInfo_DEFAULT NULL
#define appguard_AppGuardTcpInfo_connection_MSGTYPE appguard_AppGuardTcpConnection
#define appguard_AppGuardTcpInfo_ip_info_MSGTYPE appguard_AppGuardIpInfo

#define appguard_AppGuardHttpRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   original_url,      1) \
X(a, CALLBACK, REPEATED, MESSAGE,  headers,           2) \
X(a, CALLBACK, SINGULAR, STRING,   method,            3) \
X(a, CALLBACK, OPTIONAL, STRING,   body,              4) \
X(a, CALLBACK, REPEATED, MESSAGE,  query,             5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  tcp_info,        100)
#define appguard_AppGuardHttpRequest_CALLBACK pb_default_field_callback
#define appguard_AppGuardHttpRequest_DEFAULT NULL
#define appguard_AppGuardHttpRequest_headers_MSGTYPE appguard_AppGuardHttpRequest_HeadersEntry
#define appguard_AppGuardHttpRequest_query_MSGTYPE appguard_AppGuardHttpRequest_QueryEntry
#define appguard_AppGuardHttpRequest_tcp_info_MSGTYPE appguard_AppGuardTcpInfo

#define appguard_AppGuardHttpRequest_HeadersEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define appguard_AppGuardHttpRequest_HeadersEntry_CALLBACK pb_default_field_callback
#define appguard_AppGuardHttpRequest_HeadersEntry_DEFAULT NULL

#define appguard_AppGuardHttpRequest_QueryEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define appguard_AppGuardHttpRequest_QueryEntry_CALLBACK pb_default_field_callback
#define appguard_AppGuardHttpRequest_QueryEntry_DEFAULT NULL

#define appguard_AppGuardHttpResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   code,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  headers,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  tcp_info,        100)
#define appguard_AppGuardHttpResponse_CALLBACK pb_default_field_callback
#define appguard_AppGuardHttpResponse_DEFAULT NULL
#define appguard_AppGuardHttpResponse_headers_MSGTYPE appguard_AppGuardHttpResponse_HeadersEntry
#define appguard_AppGuardHttpResponse_tcp_info_MSGTYPE appguard_AppGuardTcpInfo

#define appguard_AppGuardHttpResponse_HeadersEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define appguard_AppGuardHttpResponse_HeadersEntry_CALLBACK pb_default_field_callback
#define appguard_AppGuardHttpResponse_HeadersEntry_DEFAULT NULL

#define appguard_AppGuardSmtpRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  headers,           1) \
X(a, CALLBACK, OPTIONAL, STRING,   body,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  tcp_info,        100)
#define appguard_AppGuardSmtpRequest_CALLBACK pb_default_field_callback
#define appguard_AppGuardSmtpRequest_DEFAULT NULL
#define appguard_AppGuardSmtpRequest_headers_MSGTYPE appguard_AppGuardSmtpRequest_HeadersEntry
#define appguard_AppGuardSmtpRequest_tcp_info_MSGTYPE appguard_AppGuardTcpInfo

#define appguard_AppGuardSmtpRequest_HeadersEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define appguard_AppGuardSmtpRequest_HeadersEntry_CALLBACK pb_default_field_callback
#define appguard_AppGuardSmtpRequest_HeadersEntry_DEFAULT NULL

#define appguard_AppGuardSmtpResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   code,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  tcp_info,        100)
#define appguard_AppGuardSmtpResponse_CALLBACK NULL
#define appguard_AppGuardSmtpResponse_DEFAULT NULL
#define appguard_AppGuardSmtpResponse_tcp_info_MSGTYPE appguard_AppGuardTcpInfo

#define appguard_AppGuardResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    policy,            2)
#define appguard_AppGuardResponse_CALLBACK NULL
#define appguard_AppGuardResponse_DEFAULT NULL

#define appguard_AppGuardTcpResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  tcp_info,          1)
#define appguard_AppGuardTcpResponse_CALLBACK NULL
#define appguard_AppGuardTcpResponse_DEFAULT NULL
#define appguard_AppGuardTcpResponse_tcp_info_MSGTYPE appguard_AppGuardTcpInfo

extern const pb_msgdesc_t appguard_AppGuardTcpConnection_msg;
extern const pb_msgdesc_t appguard_AppGuardIpInfo_msg;
extern const pb_msgdesc_t appguard_AppGuardTcpInfo_msg;
extern const pb_msgdesc_t appguard_AppGuardHttpRequest_msg;
extern const pb_msgdesc_t appguard_AppGuardHttpRequest_HeadersEntry_msg;
extern const pb_msgdesc_t appguard_AppGuardHttpRequest_QueryEntry_msg;
extern const pb_msgdesc_t appguard_AppGuardHttpResponse_msg;
extern const pb_msgdesc_t appguard_AppGuardHttpResponse_HeadersEntry_msg;
extern const pb_msgdesc_t appguard_AppGuardSmtpRequest_msg;
extern const pb_msgdesc_t appguard_AppGuardSmtpRequest_HeadersEntry_msg;
extern const pb_msgdesc_t appguard_AppGuardSmtpResponse_msg;
extern const pb_msgdesc_t appguard_AppGuardResponse_msg;
extern const pb_msgdesc_t appguard_AppGuardTcpResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define appguard_AppGuardTcpConnection_fields &appguard_AppGuardTcpConnection_msg
#define appguard_AppGuardIpInfo_fields &appguard_AppGuardIpInfo_msg
#define appguard_AppGuardTcpInfo_fields &appguard_AppGuardTcpInfo_msg
#define appguard_AppGuardHttpRequest_fields &appguard_AppGuardHttpRequest_msg
#define appguard_AppGuardHttpRequest_HeadersEntry_fields &appguard_AppGuardHttpRequest_HeadersEntry_msg
#define appguard_AppGuardHttpRequest_QueryEntry_fields &appguard_AppGuardHttpRequest_QueryEntry_msg
#define appguard_AppGuardHttpResponse_fields &appguard_AppGuardHttpResponse_msg
#define appguard_AppGuardHttpResponse_HeadersEntry_fields &appguard_AppGuardHttpResponse_HeadersEntry_msg
#define appguard_AppGuardSmtpRequest_fields &appguard_AppGuardSmtpRequest_msg
#define appguard_AppGuardSmtpRequest_HeadersEntry_fields &appguard_AppGuardSmtpRequest_HeadersEntry_msg
#define appguard_AppGuardSmtpResponse_fields &appguard_AppGuardSmtpResponse_msg
#define appguard_AppGuardResponse_fields &appguard_AppGuardResponse_msg
#define appguard_AppGuardTcpResponse_fields &appguard_AppGuardTcpResponse_msg

/* Maximum encoded size of messages (where known) */
/* appguard_AppGuardTcpConnection_size depends on runtime parameters */
/* appguard_AppGuardIpInfo_size depends on runtime parameters */
/* appguard_AppGuardTcpInfo_size depends on runtime parameters */
/* appguard_AppGuardHttpRequest_size depends on runtime parameters */
/* appguard_AppGuardHttpRequest_HeadersEntry_size depends on runtime parameters */
/* appguard_AppGuardHttpRequest_QueryEntry_size depends on runtime parameters */
/* appguard_AppGuardHttpResponse_size depends on runtime parameters */
/* appguard_AppGuardHttpResponse_HeadersEntry_size depends on runtime parameters */
/* appguard_AppGuardSmtpRequest_size depends on runtime parameters */
/* appguard_AppGuardSmtpRequest_HeadersEntry_size depends on runtime parameters */
/* appguard_AppGuardSmtpResponse_size depends on runtime parameters */
/* appguard_AppGuardTcpResponse_size depends on runtime parameters */
#define APPGUARD_APPGUARD_PB_H_MAX_SIZE          appguard_AppGuardResponse_size
#define appguard_AppGuardResponse_size           2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
